### ISSUE TITLE
Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [tikv/website#326]
This issue is part of a CNCF-wide effort to upgrade project websites to GA4 since **Google has deprecated Universal Analytics** (UA). For more details, see:

- https://github.com/cncf/techdocs/issues/108, including reference to a suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Tasks

- [x] Create a GA4 site tag under the **CNCF projects** account using the GA4 migration assistant.
  The new GA4 stream measurement ID is: **`G-K9DYZWQ75Q`**

- [ ] Confirm that the GA4 site tag is receiving events
- [ ] Confirm that the UA site tag is still receiving events

### Later

- Drop UA ID

/cc @caniszczyk @nate-double-u

---

### Pre-migration analytics info for the website

- UA ID `UA-130734531-1` is registered via [gtag.js]

[connect]: https://support.google.com/analytics/answer/9973999
[gtag.js]: https://developers.google.com/analytics/devguides/collection/gtagjs
[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by chalin** [comment]
Question for maintainers: is the website hosted by Netlify? If so, can you grant me access to the Netlify account?

**Comment by chalin** [comment]
Pinging maintainers. See my questions in the previous comment.
